# Generated by Django 3.1.4 on 2020-12-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_platform', models.CharField(max_length=16)),
                ('player_platform_id', models.PositiveIntegerField(default=0)),
                ('game_coins', models.PositiveIntegerField(default=0)),
                ('game_level', models.PositiveSmallIntegerField(default=0)),
                ('game_lives', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
