# Generated by Django 5.2.7 on 2026-01-26 01:07

import django.db.models.deletion
import game_triangle_racer.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_default_life_recovery_interval', models.PositiveSmallIntegerField(default=1800)),
            ],
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=str, max_length=16, unique=True)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_quasisecret', models.BigIntegerField(default=0)),
                ('regin_stamp', models.BigIntegerField(default=0)),
                ('login_stamp', models.BigIntegerField(default=0)),
                ('start_stamp', models.BigIntegerField(default=0)),
                ('token', models.CharField(default=game_triangle_racer.helpers.default_random_string, max_length=32, unique=True)),
                ('token_expiration', models.DateTimeField(default=game_triangle_racer.helpers.datetime_now_utc)),
                ('platform', models.CharField(max_length=16)),
                ('platform_id', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=str, max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=str, max_length=16, unique=True)),
                ('price', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=str, max_length=16, unique=True)),
                ('duration', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigOfInitialPlayerCostume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.costume')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCostume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.costume')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='costumes',
            field=models.ManyToManyField(through='game_triangle_racer.PlayerCostume', to='game_triangle_racer.costume'),
        ),
        migrations.CreateModel(
            name='PlayerResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.player')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.resource')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='resources',
            field=models.ManyToManyField(through='game_triangle_racer.PlayerResource', to='game_triangle_racer.resource'),
        ),
        migrations.CreateModel(
            name='ConfigOfInitialPlayerResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_count', models.PositiveIntegerField(default=0)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.resource')),
                ('shop_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.shopset')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Planned'), (2, 'Working'), (3, 'Expired')], default=1)),
                ('start_datetime', models.DateTimeField(default=game_triangle_racer.helpers.datetime_now_utc)),
                ('remaining', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.player')),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.timer')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='timers',
            field=models.ManyToManyField(through='game_triangle_racer.PlayerTimer', to='game_triangle_racer.timer'),
        ),
        migrations.AddConstraint(
            model_name='playercostume',
            constraint=models.UniqueConstraint(fields=('player', 'costume'), name='unique_player_costume'),
        ),
        migrations.AddConstraint(
            model_name='playerresource',
            constraint=models.UniqueConstraint(fields=('player', 'resource'), name='unique_player_resource'),
        ),
        migrations.AddConstraint(
            model_name='shopsetcomponent',
            constraint=models.UniqueConstraint(fields=('shop_set', 'resource'), name='unique_shop_set_component'),
        ),
        migrations.AddConstraint(
            model_name='shopsetcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 1)), name='resource_count_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='playertimer',
            constraint=models.UniqueConstraint(fields=('player', 'timer'), name='unique_player_timer'),
        ),
    ]
