# Generated by Django 3.1.4 on 2021-01-03 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='token',
            field=models.CharField(default=str, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_lives',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
