# Generated by Django 5.2.7 on 2026-03-10 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, help_text='Количество ресурса (кучка-коллекция)')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.resource')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('count__gte', 1)), name='resource_collection_count_gte_1')],
            },
        ),
    ]
