# Generated by Django 5.2.7 on 2026-03-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0002_resourcecollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceCollection',
        ),
    ]
