# Generated by Django 3.1.4 on 2021-01-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0002_auto_20210103_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='token',
        ),
        migrations.RemoveField(
            model_name='player',
            name='token_expiration',
        ),
    ]
