# Generated by Django 3.1.4 on 2021-01-17 18:09

from django.db import migrations, models
import game_triangle_racer.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0003_auto_20210106_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='token',
            field=models.CharField(default=str, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='token_expiration',
            field=models.DateTimeField(default=game_triangle_racer.helpers.datetime_now_utc),
        ),
    ]
