# Generated by Django 5.2.7 on 2026-03-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0003_delete_resourcecollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPriceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, help_text='Количество ресурса в цене')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.resource')),
                ('shop_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppricecomponent_set', to='game_triangle_racer.shopset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop_set', 'resource'), name='unique_shop_price_component'), models.CheckConstraint(condition=models.Q(('count__gte', 1)), name='price_resource_count_gte_1')],
            },
        ),
    ]
