# Generated by Django 3.1.4 on 2021-01-17 18:18

from django.db import migrations, models
import game_triangle_racer.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0004_auto_20210117_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='token',
            field=models.CharField(default=game_triangle_racer.helpers.default_random_string, max_length=32, unique=True),
        ),
    ]
