# Generated by Django 5.2.7 on 2026-03-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0004_shoppricecomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopset',
            name='price',
        ),
    ]
