# Generated by Django 3.1.5 on 2021-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0005_auto_20210117_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Receiving Token'), (2, 'Gaming'), (3, 'Shopping')], default=0),
        ),
    ]
