# Generated by Django 3.1.6 on 2021-02-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0006_player_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_coins',
            new_name='coins',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='game_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='game_lives',
            new_name='lives',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_platform',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_platform_id',
            new_name='platform_id',
        ),
    ]
