# Generated by Django 3.1.6 on 2021-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0007_auto_20210217_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='login_stamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='regin_stamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='session_quasisecret',
            field=models.IntegerField(default=0),
        ),
    ]
