# Generated by Django 3.1.6 on 2021-03-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0008_auto_20210322_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='session_quasisecret',
            field=models.BigIntegerField(default=0),
        ),
    ]
