# Generated by Django 3.1.6 on 2021-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0009_auto_20210322_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='start_stamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
