# Generated by Django 3.1.6 on 2022-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0010_player_start_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lives',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
