# Generated by Django 3.1.6 on 2022-02-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0011_auto_20220217_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_default_max_lives', models.PositiveSmallIntegerField(default=3)),
                ('game_default_life_recovery_interval', models.PositiveSmallIntegerField(default=1800)),
            ],
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=str, max_length=16, unique=True)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=str, max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=str, max_length=16, unique=True)),
                ('price', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSetComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.resource')),
                ('shop_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.shopset')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.player')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.resource')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCostume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.costume')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.player')),
            ],
        ),
    ]
