# Generated by Django 3.1.6 on 2022-03-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0012_config_costume_playercostume_playerresource_resource_shopset_shopsetcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='costumes',
            field=models.ManyToManyField(through='game_triangle_racer.PlayerCostume', to='game_triangle_racer.Costume'),
        ),
    ]
