# Generated by Django 3.1.6 on 2022-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0013_player_costumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='resources',
            field=models.ManyToManyField(through='game_triangle_racer.PlayerResource', to='game_triangle_racer.Resource'),
        ),
    ]
