# Generated by Django 3.1.6 on 2022-03-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0014_player_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='game_default_max_lives',
        ),
        migrations.AlterField(
            model_name='playerresource',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConfigOfInitialPlayerResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_count', models.PositiveIntegerField(default=0)),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.resource', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigOfInitialPlayerCostume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.costume', unique=True)),
            ],
        ),
    ]
