# Generated by Django 3.1.6 on 2022-03-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0015_auto_20220303_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configofinitialplayercostume',
            old_name='costume_id',
            new_name='costume',
        ),
        migrations.RenameField(
            model_name='configofinitialplayerresource',
            old_name='resource_id',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='playercostume',
            old_name='costume_id',
            new_name='costume',
        ),
        migrations.RenameField(
            model_name='playercostume',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='playerresource',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='playerresource',
            old_name='resource_id',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='shopsetcomponent',
            old_name='resource_id',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='shopsetcomponent',
            old_name='shop_set_id',
            new_name='shop_set',
        ),
    ]
