# Generated by Django 3.1.6 on 2022-03-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0016_auto_20220303_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='player',
            name='level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lives',
        ),
    ]
