# Generated by Django 3.1.6 on 2022-03-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0017_auto_20220312_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
