# Generated by Django 3.1.6 on 2022-05-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0018_player_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=str, max_length=16, unique=True)),
                ('creation_stamp', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.player')),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.timer')),
            ],
        ),
    ]
