# Generated by Django 3.1.6 on 2022-05-04 18:07

from django.db import migrations, models
import game_triangle_racer.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0019_playertimer_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='creation_stamp',
        ),
        migrations.AddField(
            model_name='playertimer',
            name='creation_datetime',
            field=models.DateTimeField(default=game_triangle_racer.helpers.datetime_now_utc),
        ),
        migrations.AddField(
            model_name='playertimer',
            name='remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='playercostume',
            constraint=models.UniqueConstraint(fields=('player', 'costume'), name='unique_player_costume'),
        ),
        migrations.AddConstraint(
            model_name='playerresource',
            constraint=models.UniqueConstraint(fields=('player', 'resource'), name='unique_player_resource'),
        ),
        migrations.AddConstraint(
            model_name='playertimer',
            constraint=models.UniqueConstraint(fields=('player', 'timer'), name='unique_player_timer'),
        ),
        migrations.AddConstraint(
            model_name='shopsetcomponent',
            constraint=models.UniqueConstraint(fields=('shop_set', 'resource'), name='unique_shop_set_component'),
        ),
        migrations.AddConstraint(
            model_name='shopsetcomponent',
            constraint=models.CheckConstraint(check=models.Q(count__gte=1), name='resource_count_gte_1'),
        ),
    ]
