# Generated by Django 3.1.6 on 2022-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0020_auto_20220504_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playertimer',
            old_name='creation_datetime',
            new_name='start_datetime',
        ),
        migrations.AddField(
            model_name='player',
            name='timers',
            field=models.ManyToManyField(through='game_triangle_racer.PlayerTimer', to='game_triangle_racer.Timer'),
        ),
        migrations.AddField(
            model_name='playertimer',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
