# Generated by Django 3.1.6 on 2022-06-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0021_auto_20220511_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertimer',
            name='is_working',
        ),
        migrations.AddField(
            model_name='playertimer',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Planned'), (2, 'Working'), (3, 'Expired')], default=1),
        ),
    ]
