# Generated by Django 3.1.6 on 2022-06-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0022_auto_20220604_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configofinitialplayercostume',
            name='costume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.costume'),
        ),
        migrations.AlterField(
            model_name='configofinitialplayerresource',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_triangle_racer.resource'),
        ),
    ]
