# Generated by Django 5.2.7 on 2026-01-26 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_triangle_racer', '0024_auto_20220713_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='state',
        ),
    ]
